import Head from 'next/head'
import Image from 'next/image'
import LandingPageInfo from '../components/LandingPageInfo'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className='w-full bg-black'>
      <Head>
        <title>PortFolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <LandingPageInfo />
      </div>
    </div>
  )
}
